### ISSUE TITLE
2017 Calendars?

### ISSUE THREAD

**Issue by samhagman** [olol/lolesp-cal#7]
Hey, this website was EXACTLY what I was looking for to add TSM games to my calendar.  Were you planning on updating for the 2017 season?  Thank you.

**Comment by jhuet** [comment]
Hi @samhagman, i'm glad you like the idea behind this.

Right now this project is not updated anymore. It was retrieving information based on an older LoL eSport website (parsing the json files) and i won't have time to make it available for the actual one.

If you know a bit of PHP i'd gladly give you access to this repo.

**Comment by samhagman** [comment]
Thanks @jhuet for the response.  I unfortunately am not a PHP developer but thank you for the offer and thanks for making this and putting it out there originally, it was a nice thing to do for the community.

Maybe this will inspire me to finally make a phone app that has all the LoL dates!

Happy coding!
